if not config:
    configfile: "../config/config.yaml"



######## Load rules ########
include: "rules/aligners.smk"
include: "rules/assemblers.smk"
include: "rules/annotation.smk"
include: "rules/gtf_processing.smk"



### Get construction dictionnary from config file
samples_dic = config["samples"]
constructions_dic = {}
for sample, dic in samples_dic.items():
    constructions_dic.setdefault(dic, []).append(sample)



######## Target rule ########
rule all:
    input:
        expand(os.path.join(config['dirs']['outdir'], "alignment", "{sample}.minimap2.bam.bai"), sample=list(samples_dic.keys())),
        os.path.join(config['dirs']['outdir'], "MAGIC_SOSTAR_annotation_table_results.xlsx")
