# directories
dirs:
  constructiondir: ../tests
  indir: ../tests/fastq
  outdir: /mnt/hsf/MAGIC_demo_test

# samples
samples:
    MID20: pCAS2_RAD51D_Ex2-9

# threads
threads: 35

# options
options:
  shortread: false
  longread: true